### ISSUE TITLE
XDAI integration

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1398]
https://www.xdaichain.com/

## Tasks Web v1.5
* [x] Add xDAI to dex-js and update contracts: https://github.com/gnosis/dex-js/pull/184
* [x] Add xDAI test tokens, config, network utils, etc:  #1429
* [X] Handle TxLink (former EtherscanLink) generation  #1430 
* [x] Issue with token selection: #1435
* [x] Handle gas price estimation
* [x] Handle Wrap/Unwrap
* [x] Add "DAI logo" for wxDAI and remove DAI from the default list  https://github.com/gnosis/dex-react/pull/1487
* [X] TCR for xDAI. Ours? Will dxDAO will have it's own list? --> not needed, implemented a filter using config
* [X] Filter using config for networks with no TCR https://github.com/gnosis/dex-react/pull/1489
* [X] Add price estimation endpoint for production (pending) -->Not needed, we use web3
* [x] Make sure we use production price estimation, now that it's deployed
* [x] Wallet connect?
* [ ] Websocket connection
* [x] Add xDAI RPC field in settings page 
* [X] We changed our sorting of the token list because how we load them now. 
Should we add alphabetical order? Maybe with the exception of WETH and wxDAI, that should be shown as the first option? https://github.com/gnosis/dex-react/pull/1513
* [x] Test: Make test in IOS, Android, Desktop. Both Wallet Connect and in-app browser.
   * [ ] The Graph
   * [x] Token Load
   * [x] Workflow approve, deposit
   * [x] Workflow withdraw
   * [x] Workflow trading
   * [x] Workflow wrap/unwrap
   * [x] Workflow liquidity page 

**Not blocking web 1.5, but part of xDAI**
* [x] Review documentation, add xDAI into our docs and WIKI #1505
* [x] Telegram bot https://github.com/gnosis/dex-telegram/pull/212
* [x] Telegram bot: Allow to specify a list of addresses by network instead of a TCR. https://github.com/gnosis/dex-telegram/pull/212 made the TCR optional, but now it shows all addresses as "Maybe". It would be good to add a hardcoded list of trusted tokens by network
* [x] Further refactors, nice to have:
   * [x] Given all the changes required in the PRs, can we make it easier to add networks. Theoretically it should be as easy as add the new network in a couple of places, but there was some repetition: See https://github.com/gnosis/dex-react/pull/1429
  * [x] Improve boot of the app, handle crash

## Contract and tokens
Felix just deployed GP on XDAI.

> FYI, I deployed a new GP instance on xDAI (this time with a proper OWL token that can be burnt). The address is 0x66b89680A34394Cd73A4964AF60f56c9669C2452, WETH and USDT (bridged from mainnet) are already listed as token ID 1 and 2
The OWL I used for now can be bridged from Rinkeby (for instructions how to bridge see https://docs.google.com/document/d/1lKN97odJ1SSO6PgfoScehpL1-QrljCqd864wWlCKuTQ/edit#). I didn't yet want to bridge mainnet OWL until our implementation of the Bridge contract is final.

We can make the web compatible. Also it would be nice to also solve this issue while we are at it #283

## Services

* price-estimate-xdai.dev.gnosisdev.com

**Comment by W3stside** [comment]
Separate issues #1574 and #1573, closing
