### ISSUE TITLE
Smart quote selection

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1476]
Solving this issue will also close #1273

The issue is to break a PR that got complicated. 
We need to break #1350 into smaller ones.
Note there's also #1344 (which addresses some review comments), superseded bt #1472

This will be the first of several PR. 
Additionally, there was some other tasks related to Smart Quote Selection, that would be required. This issue includes them in the following lists.

## Part of breaking PR #1350: Smart quote in Trading Widget
PRs will be merge to the WIP "smart-quote"
* [x] Add Priorities data file - #1474
* [x] Add utiltity / Test - #1474
* [x] useCannonicalMarket hook, probably we don't need it, the util should suffice --> not needed
* [x] Review why the original PR changed this type, they are not equivalent! https://github.com/gnosis/dex-react/pull/1350/files#diff-7a5f1dde90cfb4e531bbeb45baa98158R1
* [x] Consider deleting `wasPriorityAdjusted` from the utility `getMarket`
* [x] Load priorities for tokens (in API) #1478
* [x] Make the smart selection of the market in Trade Widget #1479
* [ ] Make the smart selection of the market in Orders

##  Part of breaking PR #1350: But not part of Smart quote selection 
PR will be merged against branch "develop"
* [x] Add get best ask endpoint - #1477
* [x] Create useBestAsk hook, use it in Price suggestions
~Update hooks library~ :point_left: won't do

## Improvements of Orders
* [x] Use the smart quote selection for the orders #1491
* [x] Allows to invert the quote, per row #1491
* [x] Additionally, adds a title for further clarification of the price :) #1491
* [x] Create `SmartPrice` for showing a price and the invert logic
* [ ] Storybook for `SmartPrice`. Good to have, not required
- [x] Allow to invert the market #1494
- [x] Allow to invert the market (just limit price)
- [x] We could consider not displaying 2 prices. Maybe we find a better
- [x] Everything is more clear if we break Filled/Total into 2 columns
- [x] Add horizontal scrolling to table 
- [x] Improve layout to match Trades new layout

## Improvements in Trades
These are not part of the initial PR that it's being reworked, but are part of the Smart Market Selection tasks.

- [x] Shows the market as a canonical in Trades #1494
- [x] Implement the concept of SIDE for Trades #1494
- [x] Add units to the price #1494
- [x] Rearrange Trades/Orders Row into more readable layout
- [x] Allow to invert the market #1494
- [x] Allow to invert the market (just limit price)
- [x] We could consider not displaying 2 prices. Maybe we find a better
- [x] Everything is more clear if we break Sold/Bought into 2 columns. And we called `Amount` and `Filled` for example. Check in other exchanges and our designs for v2.0
- [x] Add horizontal scrolling to table
