### ISSUE TITLE
OBA Root

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#1500]
Root issue for all things OBA related

- [ ] Design [Fee model + basic styles] #1499 
- [ ] Uniswap app structure documentation #1501
- [ ] Uniswap attempt tx send #1502
- [ ] Uniswap work in specs #1503

Estimation: ~16
